# Generated by Django 5.0.1 on 2024-01-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
